# Generated by Django 4.2.14 on 2024-08-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('in the queue', 'в очереди'), ('running', 'выполняется'), ('completed', 'завершена')], default='in the queue', max_length=150)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
